commands:
  start: "start"
  help: "help"

buttons:
  addPic: "Add Pic"
  deletePic: "Delete Pic"
  getPic: "Get Pic"
  myTags: "My Tags"

messages:
  response:
    start: "Welcome to the Telegram handlers 'Memories'! ğŸ˜Š Here you will receive reminders of your best moments to inspire and make you smile every day. Enjoy the journey through a world of bright emotions and unforgettable moments! ğŸ‰"
    help: "Welcome to the handlers instructions! ğŸ“–\n\nâ€¢ Add your favorite photos to preserve warm memories of your best life moments. ğŸ“¸\nâ€¢ If needed, you can delete unnecessary photos. ğŸ—‘ï¸\n\nJust use the handlers commands to manage your photos. Enjoy using and storing your memories! ğŸŒŸ"
    default: "I don't understand this message. ğŸ˜• Type /start to get started or /help for instruction"
    addPhoto: "Please send the photo you would like to add. ğŸ“·"
    deletePhoto: "Please send the tag by which you want to delete the photo. âŒ"
    getPic: "Please send the tag by which you want to get the photo. ğŸ”"
    getMyTags: "Just a moment, here are all the tags you've saved for your photos ğŸ“¸"
  errors:
    err_upload_pic: "There was an error uploading your photo. Please try again. âš ï¸"
    err_upload_tag: "Failed to add tag to your photo. Please try again. âš ï¸"
    err_del_pic: "An error occurred while deleting the picture. Please try again. âš ï¸"
    err_get_tags: "failed to get tags.Try again please! âš ï¸"
  success:
    pic_saved: " Your picture has been saved successfully!âœ… Please choose a tag for it. ğŸ·ï¸"
    pic_deleted: "Your picture has been deleted successfully!ğŸ—‘ï¸"
    tag_saved: " Successfully saved tag to your pictures!âœ… "

awsConfig:
  bucket: "tgphoto-storage"
  region: "eu-central-1"

redisConfig: "redis:6379"

dbConfig:
    host: "memoryPictures-db"
    port: "5432"
    username: "postgres"
    db_name: "memory-pictures"
    ssl_mode: "disable"
